### ISSUE TITLE
Add functionality to handle AWS AMI's

### ISSUE THREAD

**Issue by hiddenillusion** [google/cloud-forensics-utils#149]
There may be situations where a forensicator needs to image/analyze an AWS AMI (e.g. someone shares an AMI with your AWS account).

This would require (at a minimum):

- the ability for the [`AWSAccount`](https://github.com/google/cloud-forensics-utils/blob/master/libcloudforensics/providers/aws/internal/account.py#L34) class to have a function to **ListImages**, **GetImageByNameOrId**
- the ability to handle the workflow of a user specifying an AMI ID > launching said AMI > stopping said AMI > identifying the associated Volumes > following the existing steps for handling a Volume

**Comment by giovannt0** [comment]
Linking to #159 which might provide some of the requested functionality.

**Comment by hacktobeer** [comment]
WIP: ListImages implemented in #160

**Comment by giovannt0** [comment]
Closed by #166 and #168
