### ISSUE TITLE
GCP API ExecuteRequest function should retrieve the next page of results using the native _next APIs functions

### ISSUE THREAD

**Issue by sa3eed3ed** [google/cloud-forensics-utils#155]
instead of implementing [pagination](https://github.com/google/cloud-forensics-utils/blob/2c5b8b50bf19f209fe77309811d466d82302b42c/libcloudforensics/providers/gcp/internal/common.py#L208) and sending the next_page token inside the ExecuteRequest function, I believe we should change this and use the native list_next and aggregatedList_next functions which are exposed by all paginating GCP API functions
EX:
Logging: http://googleapis.github.io/google-api-python-client/docs/dyn/logging_v2.entries.html
Functions: http://googleapis.github.io/google-api-python-client/docs/dyn/cloudfunctions_v1.operations.html
Compute: https://developers.google.com/resources/api-libraries/documentation/compute/v1/python/latest/compute_v1.instances.html#aggregatedList_next

I can't find any paginating api that doesn't implement {function}_next

This is not really related to this PR, will start a new issue for that.

**Comment by hacktobeer** [comment]
Had a look and it essentially means we need to start calling *another* function if the first function returns a nextpage token. So you first call list() and if it returns a nextpage token you need to start calling page_next() and we need to differentiate on the actually used API as for the compute API it's aggregatedList() and aggregatedList_next().

The current code is pretty clean imo.

**Comment by sa3eed3ed** [comment]
agree with @hacktobeer's commnet and closing
