### ISSUE TITLE
Regex testing string length

### ISSUE THREAD

**Issue by binglot** [google/cloud-forensics-utils#172]
Hey folks, the file `libcloudforensics/providers/aws/internal/common.py` has a regex that seems to be testing length of the string. Is that really necessary?

`REGEX_TAG_VALUE = re.compile('^.{1,255}$')`

**Comment by giovannt0** [comment]
Hey Bart! This is used in `account.py` and `ebs.py` under AWS's internal module to ensure that tag values (which can be user supplied) are <255 chars as per AWS requirements.

**Comment by tomchop** [comment]
I think what Bart means is why just not do `len(blah) < 255`.

**Comment by giovannt0** [comment]
Ah, I see. Initially this was to be consistent with the way we make sure naming convention are respected for other cloud providers. For this particular case I agree it is a little overkill. Should we get rid of it?

**Comment by binglot** [comment]
Thanks for jumping in Tom, that's exactly what I meant. It's certainly not a big deal, using len() might be more elegant.
