### ISSUE TITLE
Possible bug in checking the number of volumes to attach

### ISSUE THREAD

**Issue by binglot** [google/cloud-forensics-utils#190]
The `aws_cli.py` file checks the number of provided volumes to attach, as shown in the below code:

https://github.com/google/cloud-forensics-utils/blob/d50d4e36dca0fe450e286e351b2a4bf3942b8786/examples/aws_cli.py#L118-L129

It seems that `args.attach_volumes` is a string, so shouldn't the check look like this instead?

```
  if args.attach_volumes and len(args.attach_volumes.split(',')) > 11:
    print('error: --attach_volumes must be < 11')
    return
```

**Comment by hacktobeer** [comment]
Yes it should, good catch. Also (e2e) tests tests tests (me talking to myself).
