### ISSUE TITLE
Support other sources of credentials for boto3

### ISSUE THREAD

**Issue by EmilienCourt** [google/cloud-forensics-utils#202]
Hi,

Right now, `libcloudforensics` only supports credentials read from the `~/.aws/config` file.

Would you consider adding support for other sources ?

[This page](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#configuring-credentials) lists the configuration possibilities for boto3, which includes passing credentials as parameters when creating a Session object :
```python
import boto3

session = boto3.Session(
    aws_access_key_id=ACCESS_KEY,
    aws_secret_access_key=SECRET_KEY,
    aws_session_token=SESSION_TOKEN
)
```

Looking at the code from `account.py` ([here](https://github.com/google/cloud-forensics-utils/blob/master/libcloudforensics/providers/aws/internal/account.py#L77)), it seems it would only require minor changes (for example an optional switch to use credentials read from CLI/when using the library) to configure boto3 this way.

This would make `libclouforensics` usable without AWS CLI and without a configuration file, which stores credentials on disk.

This could be useful when integrating `libcloudforensics` in other projects, which might handle tokens and keys without using the CLI (using [get_session_token](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sts.html#STS.Client.get_session_token) from boto3 for example).

Regards,

**Comment by giovannt0** [comment]
Hi @EmilienCourt, thank you for your suggestion. I've opened #203 which should help you use `libcloudforensics` with `get_session_token`. Feel free to chat with us in our slack channel if you have comments or other suggestions (https://github.com/open-source-dfir/slack)

**Comment by hacktobeer** [comment]
Functionality to use AWS credentials as function parameters should also be added to forensics.py.

**Comment by giovannt0** [comment]
For us to have this for both source and dest account would mean an additional 6 parameters, which I'm not a big fan of (this is why I left out the forensics module from the PR in the first place). IMHO it will make things a little messy with so many parameters / options for the CLI

**Comment by EmilienCourt** [comment]
Agree with @giovannt0, did not realize it would bring that much parameters

**Comment by hacktobeer** [comment]
Makes sense, had not considered both source and destination.
