### ISSUE TITLE
Feature Request: Check for "Deletion Protection Enabled" and disable

### ISSUE THREAD

**Issue by GreenStorm-Code** [google/cloud-forensics-utils#283]
Sometimes we aren't able to delete instances because Deletion Protection is enabled. This has to be manually turned off. If when deleting an instance we were able to check iteratively for a list of instances where it was enabled and then disable, it would make mass deletion easier.

Something like you pass the project ID and it checks the compute instance API, lists all instances then iteratively passes them back to check.

**Comment by hiddenillusion** [comment]
This would be useful in AWS as well (EC2 termination protection)

**Comment by giovannt0** [comment]
@GreenStorm-Code @hiddenillusion taken care of in both GCP and AWS in #331.
