### ISSUE TITLE
Only provide a LocationConstraint when creating an S3 bucket if region != us-east-1

### ISSUE THREAD

**Issue by hiddenillusion** [google/cloud-forensics-utils#305]
`us-east-1` is the default region where the S3 bucket will get created if a LocationConstraint isn't provided.

However, there's an issue that causes the CreateBucket operation to fail if `us-east-1` is explicitly placed as the LocationContraint:

```
Could not create bucket <BUCKET_NAME>t: An error occurred (InvalidLocationConstraint) when calling the CreateBucket operation: The specified location-constraint is not valid
```

[S3.CreateBucket()](https://github.com/google/cloud-forensics-utils/blob/main/libcloudforensics/providers/aws/internal/s3.py#L83) should check what the values of `region` & `self.aws_account.default_region` are and skip adding the LocationConstraint if `us-east-1` is provided

**Comment by Fryyyyy** [comment]
https://github.com/boto/boto3/issues/125  👌
