### ISSUE TITLE
instance.Delete() fails if no VPC is attached

### ISSUE THREAD

**Issue by cugu** [google/cloud-forensics-utils#462]
instance.Delete() fails if no VPC is attached.

Failing example code snippet:
```python
instance = account.ec2.GetInstanceById(instance_id)
instance.Delete()
```

A key error  is thrown at:
https://github.com/google/cloud-forensics-utils/blob/a71b13c3a7108e4d37879007617203c5e34170ff/libcloudforensics/providers/aws/internal/ec2.py#L250

**Comment by Fryyyyy** [comment]
I am finding it hard to repro this as its not currently possible to create an EC2 instance without a VPC, as far as I can tell

**Comment by Fryyyyy** [comment]
However it doesn't appear as though VPC is required for the delete procedure, so I don't see why we can't just set a default for this value if it doesn't exist

**Comment by cugu** [comment]
Not sure how this occurred, but had this happen in an investigation. Thanks for the fix!
