### ISSUE TITLE
Migrate loops body to separate method

### ISSUE THREAD

**Issue by giovannt0** [google/cloud-forensics-utils#80]
`while not have_all_tokens:` kinda loops, across gcp.py and aws.py

**Comment by hacktobeer** [comment]
As per discussion, let's move this to the provider common.py in a generic pagination fetch result function.

**Comment by giovannt0** [comment]
Let's tackle this in two steps to accommodate incoming changes from @sa3eed3ed :

- [ ] AWS: Addressed in #110
- [ ] GCP
