### ISSUE TITLE
Add start/end time filter support to log acquisitions

### ISSUE THREAD

**Issue by hacktobeer** [google/cloud-forensics-utils#81]
- [x] AWS
- [ ] GCP

**Comment by hacktobeer** [comment]
AWS done, GCP can be done in filter. 
TODO: Create PR to do it outside of the raw filter for GCP.

**Comment by giovannt0** [comment]
@hacktobeer have we added that already?

**Comment by hacktobeer** [comment]
No, net yet. Let me work on that this week.
